### ISSUE TITLE
Setup the [Catch2](https://github.com/catchorg/Catch2), Test Framework

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#13]
## Specifications
The tests ...

- Must use the [Catch2](https://github.com/catchorg/Catch2) library (#10)
- Must be generated inside the `root/test` directory
- Must be generated using a target from [Meson](https://mesonbuild.com), the build system (#6)
- Must not throw any error nor warning during the tests execution
- Must somehow show the results of the tests execution
- Must support the *debug* and *release* targets

## TODO
- [ ] Add the target for tests executiong inside [Meson](https://mesonbuild.com), the build system (#6)
- [ ] Code some tests
- [ ] Verify that the tests execution works
- [ ] Verify that the tests execution shows its results somehow
- [ ] Integrate the *debug* and *release* targets
