### ISSUE TITLE
Fetch Clang Version

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#31]
## Specifications
- A script isolated in its own file
- The script can either be executed or imported
- If the script is executed (standalone), then prints to `stdout` the version of the default or supplied `arg` *Clang* compiler
- If the script is imported, then supply a function to fetch the version of the default or supplied `arg` *Clang* compiler
- The data model used to represent the version must be the `CompilerVersion` `Enum`

## TODO
- [x] Print the default compiler version when the script is executed (standalone)`
- [x] Supply a function to fetch the version of the default compiler
- [x] Interpret the version string as the `CompilerVersion` `Enum`
- [x] Use the supplied `arg` as the specified *Clang* compiler
- [x] Verify the integrity of the supplied `arg` path

## Tips
```shell
clang -dumpversion
# 11.1.0
```
