### ISSUE TITLE
Fetch MSVC Version

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#33]
## Specifications
- A script isolated in its own file
- The script can either be executed or imported
- If the script is executed (standalone), then prints to `stdout` the version of the default or supplied `arg` *MSVC* compiler
- If the script is imported, then supply a function to fetch the version of the default or supplied `arg` *MSVC* compiler
- The data model used to represent the version must be the `CompilerVersion` `Enum`

## TODO
- [x] Print the default compiler version when the script is executed (standalone)`
- [x] Supply a function to fetch the version of the default compiler
- [x] Interpret the version string as the `CompilerVersion` `Enum`
- [x] Use the supplied `arg` as the specified *MSVC* compiler

## Tips
*MSVC* : go to hardcoded path and check folder version
*BuildTools* (no *VS*) : `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\*`
*VS* : `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\*`
It's actually the *MSVC++* version, not the `_MSC_VER`!
See `C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe`

```shell
vswhere.exe -prerelease -latest -products "*" -property 'installationVersion' -requires "Microsoft.VisualStudio.Component.VC.Tools.x86.x64" "Microsoft.VisualStudio.Component.Windows10SDK.19041" "Microsoft.VisualStudio.Component.VC.CMake.Project" "Microsoft.VisualStudio.Component.TestTools.BuildTools" "Microsoft.VisualStudio.Component.VC.ASAN" "Microsoft.VisualStudio.Component.VC.Modules.x86.x64" "Microsoft.VisualStudio.Workload.VCTools"
```
