### ISSUE TITLE
Move Compiler Related Scripts Into Their Own Package

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#36]
## Specifications
- Move compiler related scripts into their own Python package

## TODO
- [x] Investigate Python modules
- [x] Create the new compiler package
- [x] Move compiler versions fetching scripts into the compiler package
- [x] Move the compiler `Enum` script into the compiler package
- [x] Move compiler version `Enum` script into the compiler package
- [x] Simplify file names
- [x] Adapt imports
- [x] Simplify method names
