### ISSUE TITLE
Fetch GCC Architecture

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#38]
## Specifications
- A script isolated in its own file
- The script can either be executed or imported
- If the script is executed (standalone), then prints to `stdout` the version of the default or supplied `arg` *GCC* compiler
- If the script is imported, then supply a function to fetch the version of the default or supplied `arg` *GCC* compiler
- The data model used to represent the architecture must be the `Architecture` `Enum`

## TODO
- [ ] Print the default compiler architecture when the script is executed (standalone)
- [ ] Supply a function to fetch the architecture of the default compiler
- [ ] Interpret the architecture string as the `Architecture` `Enum`
- [ ] Use the supplied `arg` as the specified *GCC* compiler
- [ ] Verify the integrity of the supplied `arg` path
- [ ] Assure that the supplied `arg` is actually a *GCC* compiler

## Tips
```shell
gcc -dumpmachine
# x86_64-w64-mingw32
```
