### ISSUE TITLE
Fetch Clang Architecture

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#39]
## Specifications
- A script isolated in its own file
- The script can either be executed or imported
- If the script is executed (standalone), then prints to `stdout` the version of the default or supplied `arg` *Clang* compiler
- If the script is imported, then supply a function to fetch the version of the default or supplied `arg` *Clang* compiler
- The data model used to represent the architecture must be the `Architecture` `Enum`

## TODO
- [ ] Print the default compiler architecture when the script is executed (standalone)
- [ ] Supply a function to fetch the architecture of the default compiler
- [ ] Interpret the architecture string as the `Architecture` `Enum`
- [ ] Use the supplied `arg` as the specified *Clang* compiler
- [ ] Verify the integrity of the supplied `arg` path
- [ ] Assure that the supplied `arg` is actually a *Clang* compiler

## Tips
```shell
clang -dumpmachine
# x86_64-pc-windows-msvc
```
