### ISSUE TITLE
Fetch MSVC Architecture

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#40]
## Specifications
- A script isolated in its own file
- The script can either be executed or imported
- If the script is executed (standalone), then prints to `stdout` the version of the default or supplied `arg` *MSVC* compiler
- If the script is imported, then supply a function to fetch the version of the default or supplied `arg` *MSVC* compiler
- The data model used to represent the architecture must be the `Architecture` `Enum`

## TODO
- [ ] Print the default compiler architecture when the script is executed (standalone)
- [ ] Supply a function to fetch the architecture of the default compiler
- [ ] Interpret the architecture string as the `Architecture` `Enum`
- [ ] Use the supplied `arg` as the specified *MSVC* compiler
- [ ] Verify the integrity of the supplied `arg` path
- [ ] Assure that the supplied `arg` is actually a *MSVC* compiler

## Tips
*MSVC* : go to hardcoded path and check folder version
*BuildTools* (no *VS*) : `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\*`
*VS* : `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\*`
It's actually the *MSVC++* version, not the `_MSC_VER`!
