### ISSUE TITLE
Read Requirements for finding installed matching MSVC compilers

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#45]
## Specifications
- A script isolated in its own file
- The script can either be executed or imported
- If the script is executed (standalone), then prints to `stdout` the *MSVC* compiler requirements from the default property file (`.ini`)
- If the script is executed (standalone) and an argument is supplied, then prints to `stdout` the *MSVC* compiler requirements from the property file (`.ini`) with the supplied argument as path
- If the script is imported, then supply a function to read *MSVC* compiler requirements from the default property file (`.ini`)
- If the script is imported and an argument is supplied, then supply a function to read *MSVC* compiler requirements from the property file (`.ini`) with the supplied argument as path

## TODO
- [ ] Print the compiler requirements from the default property file (`.ini`) when the script is executed (standalone)`
- [ ] Print the compiler requirements from the supplied property file (`.ini`) as path as an argument when the script is executed (standalone)`
- [ ] Supply a function to find the compiler requirements from the default property file (`.ini`)
- [ ] Supply a function to find the compiler requirements from the supplied as path as argument property file (`.ini`)
