### ISSUE TITLE
Use Installed Compiler Versions for Build Directories

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#57]
## Specifications
- Use actual compiler versions for build directories
    - *GCC* #30
    - *Clang* #31
    - *MSVC* #33

## TODO
- [x] Use the supported installed *GCC* #30 version
- [x] Use the supported installed *Clang* #31 version
- [x] Use the supported installed *MSVC* #33 version

**Comment by benoit-dubreuil** [comment]
Had problems with cyclic dependencies
