### ISSUE TITLE
Create / Setup Build Directories 

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#58]
## Specifications
- Create all [Meson](https://mesonbuild.com) build directories
- If missing, create the parent build directory
- The directory names must indicate the OS
- The directory names must indicate the architecture
- The directory names must indicate the compiler family
- The directory names must indicate the compiler version
    - No need to use the actual compiler versions
- The directory names must indicate the build type

## TODO
- [x] Fetch the OS
- [x] Fetch the architecture
- [x] Fetch the compiler family
- [x] Fetch the compiler version
- [x] Fetch the build type
- [x] If missing, create the parent build directory
- [x] Directly inside [Meson](https://mesonbuild.com)'s `setup` command automation scripts
- [x] Create a build directory
- [x] Create all build directories

**Comment by benoit-dubreuil** [comment]
I learnt how to create true `mixins` and improved the errors
