### ISSUE TITLE
Clean Parent Build Directory

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#59]
## Specifications
- Supply a *CLI* callable script
- Supply a script package
- Delete the parent build directory and thus delete every sub build directories

## TODO
- [x] Delete the parent build directory
- [x] Exit 0 if it was successfully deleted
- [x] Exit 1 if the root doesn't exist
- [x] Exit 2 if it doesn't exist
- [x] Exit > 2 for any other `OSError`
- [x] Supply the script package
- [x] Supply the *CLI* callable script 

## Tips
[`shutil.rmtree`](https://docs.python.org/3/library/shutil.html#shutil.rmtree)
