### ISSUE TITLE
Supply Native Machine Files to Build System

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/template-repo-cpp-ecosystem#61]
## Specifications
- Use [Meson](https://mesonbuild.com)'s `setup` command
- Supply global machine files
- Supply global native machine files
- Supply compiler specific native machine files
- Supply build type specific native machine files

## TODO
- [x] Supply global machine files
- [x] Supply global native machine files
- [x] Supply compiler specific native machine files
- [x] Supply build type specific native machine files
